-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 05, 2026 at 08:03 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.3.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `resume_analyzer`
--

DELIMITER $$
--
-- Procedures
--
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_get_resume` (IN `MODE` INT, IN `p_id` BIGINT)   BEGIN
	IF MODE = 1
    THEN
    	BEGIN 
    		SELECT  resume_content
            FROM 	tbl_resume_analyses
            WHERE 	id = p_id
            ORDER BY created_at DESC
            LIMIT 1; 
		END;
    END IF;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_insert_resume` (IN `MODE` INT, IN `p_resume_content` LONGTEXT, IN `p_job_description` TEXT)   BEGIN
	IF MODE = 1
    THEN
    	BEGIN 
    		INSERT INTO tbl_resume_analyses (resume_content
        	                             	,job_description)
    		VALUES 							(p_resume_content
            	                         	,p_job_description);
		END;
    END IF;
END$$

DELIMITER ;

-- --------------------------------------------------------

--
-- Table structure for table `tbl_resume_analyses`
--

CREATE TABLE `tbl_resume_analyses` (
  `id` int(11) NOT NULL,
  `resume_content` longtext DEFAULT NULL,
  `job_description` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tbl_resume_analyses`
--

INSERT INTO `tbl_resume_analyses` (`id`, `resume_content`, `job_description`, `created_at`) VALUES
(1, 'asdsad', 'asdsad', '2026-02-02 10:42:23'),
(2, '<!DOCTYPE html>\r\n<!-- Generated by PHPWord -->\r\n<html lang=\'en-PH\'>\r\n<head>\r\n<meta charset=\"UTF-8\" />\r\n<title>PHPWord</title>\r\n<meta name=\"author\" content=\"Mariel Monteron\" />\r\n<style>\r\nbody {font-family: \'Arial\'; font-size: 12pt; color: #000000;}\r\n* {font-family: \'Arial\'; font-size: 12pt; color: #000000;}\r\na.NoteRef {text-decoration: none;}\r\nhr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}\r\ntable {border: 1px solid black; border-spacing: 0px; width : 100%;}\r\ntd {border: 1px solid black;}\r\np, .Normal {margin-bottom: 8pt;}\r\nh1 {font-size: 20pt; color: #0F4761;}\r\nh1 {margin-top: 18pt; margin-bottom: 4pt;}\r\nh2 {font-size: 16pt; color: #0F4761;}\r\nh2 {margin-top: 8pt; margin-bottom: 4pt;}\r\nh3 {font-size: 14pt; color: #0F4761;}\r\nh3 {margin-top: 8pt; margin-bottom: 4pt;}\r\nh4 {color: #0F4761; font-style: italic;}\r\nh4 {margin-top: 4pt; margin-bottom: 2pt;}\r\nh5 {color: #0F4761;}\r\nh5 {margin-top: 4pt; margin-bottom: 2pt;}\r\nh6 {color: #595959; font-style: italic;}\r\nh6 {margin-top: 2pt; margin-bottom: 0pt;}\r\nh7 {color: #595959;}\r\nh7 {margin-top: 2pt; margin-bottom: 0pt;}\r\nh8 {color: #272727; font-style: italic;}\r\nh8 {margin-bottom: 0pt;}\r\nh9 {color: #272727;}\r\nh9 {margin-bottom: 0pt;}\r\n.Normal Table {table-layout: auto;}\r\n.Heading 1 Char {font-size: 20pt; color: #0F4761;}\r\n.Heading 2 Char {font-size: 16pt; color: #0F4761;}\r\n.Heading 3 Char {font-size: 14pt; color: #0F4761;}\r\n.Heading 4 Char {color: #0F4761; font-style: italic;}\r\n.Heading 5 Char {color: #0F4761;}\r\n.Heading 6 Char {color: #595959; font-style: italic;}\r\n.Heading 7 Char {color: #595959;}\r\n.Heading 8 Char {color: #272727; font-style: italic;}\r\n.Heading 9 Char {color: #272727;}\r\n.Title {font-size: 28pt;}\r\n.Title Char {font-size: 28pt;}\r\n.Subtitle {font-size: 14pt; color: #595959;}\r\n.Subtitle Char {font-size: 14pt; color: #595959;}\r\n.Quote {color: #404040; font-style: italic;}\r\n.Quote Char {color: #404040; font-style: italic;}\r\n.List Paragraph {margin-left: 0.5in; margin-right: 0in;}\r\n.Intense Emphasis {color: #0F4761; font-style: italic;}\r\n.Intense Quote {color: #0F4761; font-style: italic;}\r\n.Intense Quote Char {color: #0F4761; font-style: italic;}\r\n.Intense Reference {color: #0F4761; font-weight: bold; font-variant: small-caps;}\r\nbody > div + div {page-break-before: always;}\r\ndiv > *:first-child {page-break-before: auto;}\r\n@page page1 {size: A4 portrait; margin-right: 1in; margin-left: 1in; margin-top: 1in; margin-bottom: 1in; }\r\n</style>\r\n</head>\r\n<body>\r\n<div style=\'page: page1\'>\r\n<p>1<span style=\"vertical-align: super;\">st</span> PURCHASING SCENARIO</p>\r\n<p>Purchase Order Foreign </p>\r\n\r\n<p>Input Supplier (</p>\r\n<p>KOWA-EMORI PHILIPPINES INC.</p>\r\n<p>)</p>\r\n\r\n<p>Input Ship to (Raw Materials P1)</p>\r\n\r\n<p>Input PO Type (foreign)</p>\r\n\r\n<p>Input PO date (15 Nov 2025)</p>\r\n\r\n<p>Input Due date (15 Nov 2025)</p>\r\n\r\n<p>Input Currency (dollar)</p>\r\n\r\n<p>Input Credit Terms (cash)</p>\r\n\r\n<p>Input VAT Code (VAT-ZERO)</p>\r\n\r\n<p>Select Ship Via (Air)</p>\r\n\r\n<p>Supplier PO Reference (none)</p>\r\n\r\n<p>Input Item numbers (</p>\r\n<p>236964</p>\r\n<p>)</p>\r\n\r\n<p>Input item description (</p>\r\n<p>4104RE0212B</p>\r\n<p>)</p>\r\n\r\n<p>Input Item quantity (4,500.00)</p>\r\n\r\n<p>Input Item unit price </p>\r\n<p>( 0.0500</p>\r\n<p>)</p>\r\n\r\n<p>Input Remarks (</p>\r\n<p>NOV RCT</p>\r\n<p>)</p>\r\n\r\n<p>Other charges (none)</p>\r\n\r\n<p>Purchaser Order Approval</p>\r\n<p> – approved</p>\r\n\r\n<p>Import Shipment</p>\r\n\r\n<p>GENERAL TAB</p>\r\n\r\n<p>Select Supplier (</p>\r\n<p>KOWA-EMORI PHILIPPINES INC.</p>\r\n<p>)</p>\r\n\r\n<p>Select Ship to Site (Raw materials p2)</p>\r\n\r\n<p>Select Incoterms (</p>\r\n<p>Cost,Insurance</p>\r\n<p> and Freight (CIF)</p>\r\n\r\n<p>Select Transaction Currency </p>\r\n<p>( Dollar</p>\r\n<p>)</p>\r\n\r\n<p>Payment  Mode</p>\r\n<p> (Bank Transfer)</p>\r\n\r\n<p>Select Ship Via (Air)</p>\r\n\r\n<p>ITEM TAB</p>\r\n\r\n<p>Select PO of KOWA-EMORI PHILIPPINES</p>\r\n\r\n<p>CHARGES TAB</p>\r\n\r\n<p>No charges</p>\r\n\r\n<p>&nbsp;</p>\r\n<div style=\"page-break-before: always; height: 0; margin: 0; padding: 0; overflow: hidden;\">&#160;</div>\r\n<p><br />\r\n</p>\r\n<p>2nd PURCHASING SCENARIO</p>\r\n<p>Purchase Order Foreign </p>\r\n\r\n<p>Input Supplier (</p>\r\n<p>SUNG HYUNG PRECISION CO., INC.</p>\r\n<p>)</p>\r\n\r\n<p>Input Ship to (Raw Materials P1)</p>\r\n\r\n<p>Input PO Type (foreign)</p>\r\n\r\n<p>Input PO date (22 Oct 2025)</p>\r\n\r\n<p>Input Due date (22 Oct 2025)</p>\r\n\r\n<p>Input Currency (dollar)</p>\r\n\r\n<p>Input Credit Terms (cash)</p>\r\n\r\n<p>Input VAT Code (VAT-ZERO)</p>\r\n\r\n<p>Select Ship Via (Air)</p>\r\n\r\n<p>Supplier PO Reference (none)</p>\r\n\r\n<p>Input Item numbers (</p>\r\n<p>186930</p>\r\n<p>, </p>\r\n<p>186933</p>\r\n<p>)</p>\r\n\r\n<p>Input item description (</p>\r\n<p>4067RE0202A</p>\r\n<p>, </p>\r\n<p>4067RE0201A</p>\r\n<p>)</p>\r\n\r\n<p>Input Item quantity (500.00</p>\r\n<p>, </p>\r\n<p>500</p>\r\n<p>.00</p>\r\n<p>)</p>\r\n\r\n<p>Input Item unit price (0.0</p>\r\n<p>600, 0.0700</p>\r\n<p>)</p>\r\n\r\n<p>Input Remarks (</p>\r\n<p>No remarks</p>\r\n<p>)</p>\r\n\r\n<p>Other charges (none)</p>\r\n\r\n<p>Purchaser Order Approval</p>\r\n<p> – approved</p>\r\n\r\n<p>Import Shipment</p>\r\n\r\n<p>GENERAL TAB</p>\r\n\r\n<p>Select Supplier (</p>\r\n<p>SUNG HYUNG PRECISION CO., INC</p>\r\n<p>.</p>\r\n<p>)</p>\r\n\r\n<p>Select Ship to Site (Raw materials p</p>\r\n<p>1</p>\r\n<p>)</p>\r\n\r\n<p>Select Incoterms (Cost,</p>\r\n<p>&nbsp;</p>\r\n<p>Insurance and Freight (CIF)</p>\r\n\r\n<p>Select Transaction Currency (</p>\r\n<p>d</p>\r\n<p>ollar)</p>\r\n\r\n<p>Payment  Mode</p>\r\n<p> (Bank Transfer)</p>\r\n\r\n<p>Select Ship Via (Air)</p>\r\n\r\n<p>ITEM TAB</p>\r\n\r\n<p>Select PO of </p>\r\n<p>SUNG HYUNG PRECISION CO., INC</p>\r\n\r\n<p>CHARGES TAB</p>\r\n\r\n<p>No charges</p>\r\n\r\n<p>&nbsp;</p>\r\n<p>&nbsp;</p>\r\n</div>\r\n</body>\r\n</html>\r\n', 'asdasdasdasd', '2026-02-05 19:59:27');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tbl_resume_analyses`
--
ALTER TABLE `tbl_resume_analyses`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tbl_resume_analyses`
--
ALTER TABLE `tbl_resume_analyses`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
